# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :title
#relative_permalinks: true

# Setup
title:               Fieg
tagline:             ''
description:         ''
url:                 http://fieg.nl
baseurl:             ''
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
paginate:            15
paginate_path:       "page:num"

# About/contact
author:
  name:              Jeroen
  url:               https://twitter.com/fieg
  email:             i.am.fieg@gmail.com

# Custom vars
version:             1.0.0
